"""Generate entity_registry.json with all 249 countries/territories."""
import json

# Format: (name, iso, type, parent, continent, sub_region, capital, pop_millions, languages, currency, size_class, neighbors, comparisons)
# type: S=sovereign, T=territory, D=dependency, SAR=special admin region, DI=disputed
# size: L=large(>20M), M=medium(1-20M), S=small(<1M)

ENTITIES = [
# ============ AFRICA ============
("Afghanistan","AF","S","","asia","southern-asia","Kabul",40.1,"Pashto,Dari","AFN","L",["Iran","Pakistan","Turkmenistan","Uzbekistan","Tajikistan","China"],["Pakistan","Iran"]),
("Albania","AL","S","","europe","southern-europe","Tirana",2.8,"Albanian","ALL","M",["Montenegro","Kosovo","North Macedonia","Greece"],["North Macedonia","Kosovo"]),
("Algeria","DZ","S","","africa","northern-africa","Algiers",45.6,"Arabic,Berber","DZD","L",["Morocco","Tunisia","Libya","Niger","Mali","Mauritania","Western Sahara"],["Morocco","Tunisia"]),
("Andorra","AD","S","","europe","southern-europe","Andorra la Vella",0.08,"Catalan","EUR","S",["France","Spain"],["Monaco","Liechtenstein"]),
("Angola","AO","S","","africa","middle-africa","Luanda",35.6,"Portuguese","AOA","L",["DR Congo","Republic of Congo","Zambia","Namibia"],["Mozambique","DR Congo"]),
("Antigua and Barbuda","AG","S","","north-america","caribbean","St. John's",0.1,"English","XCD","S",["Saint Kitts and Nevis"],["Barbuda","Saint Kitts and Nevis"]),
("Argentina","AR","S","","south-america","south-america","Buenos Aires",46.0,"Spanish","ARS","L",["Chile","Bolivia","Paraguay","Brazil","Uruguay"],["Chile","Brazil"]),
("Armenia","AM","S","","asia","western-asia","Yerevan",3.0,"Armenian","AMD","M",["Georgia","Azerbaijan","Iran","Turkey"],["Georgia","Azerbaijan"]),
("Australia","AU","S","","oceania","australia-new-zealand","Canberra",26.4,"English","AUD","L",["Indonesia","Papua New Guinea","New Zealand"],["New Zealand","Canada"]),
("Austria","AT","S","","europe","western-europe","Vienna",9.1,"German","EUR","M",["Germany","Czech Republic","Slovakia","Hungary","Slovenia","Italy","Switzerland","Liechtenstein"],["Switzerland","Germany"]),
("Azerbaijan","AZ","S","","asia","western-asia","Baku",10.2,"Azerbaijani","AZN","M",["Russia","Georgia","Armenia","Iran","Turkey"],["Armenia","Georgia"]),
("Bahamas","BS","S","","north-america","caribbean","Nassau",0.41,"English","BSD","S",["United States","Cuba"],["Bermuda","Turks and Caicos"]),
("Bahrain","BH","S","","asia","western-asia","Manama",1.5,"Arabic","BHD","M",["Saudi Arabia","Qatar"],["Qatar","Kuwait"]),
("Bangladesh","BD","S","","asia","southern-asia","Dhaka",172.0,"Bengali","BDT","L",["India","Myanmar"],["India","Pakistan"]),
("Barbados","BB","S","","north-america","caribbean","Bridgetown",0.28,"English","BBD","S",["Saint Lucia","Saint Vincent and the Grenadines"],["Trinidad and Tobago","Jamaica"]),
("Belarus","BY","S","","europe","eastern-europe","Minsk",9.4,"Belarusian,Russian","BYN","M",["Russia","Ukraine","Poland","Lithuania","Latvia"],["Ukraine","Lithuania"]),
("Belgium","BE","S","","europe","western-europe","Brussels",11.7,"Dutch,French,German","EUR","M",["France","Germany","Luxembourg","Netherlands"],["Netherlands","Luxembourg"]),
("Belize","BZ","S","","north-america","central-america","Belmopan",0.41,"English","BZD","S",["Mexico","Guatemala"],["Guatemala","Honduras"]),
("Benin","BJ","S","","africa","western-africa","Porto-Novo",13.4,"French","XOF","M",["Togo","Burkina Faso","Niger","Nigeria"],["Togo","Ghana"]),
("Bhutan","BT","S","","asia","southern-asia","Thimphu",0.78,"Dzongkha","BTN","S",["China","India"],["Nepal","Sikkim"]),
("Bolivia","BO","S","","south-america","south-america","Sucre",12.1,"Spanish,Quechua,Aymara","BOB","M",["Brazil","Paraguay","Argentina","Chile","Peru"],["Peru","Paraguay"]),
("Bosnia and Herzegovina","BA","S","","europe","southern-europe","Sarajevo",3.2,"Bosnian,Croatian,Serbian","BAM","M",["Croatia","Serbia","Montenegro"],["Serbia","Croatia"]),
("Botswana","BW","S","","africa","southern-africa","Gaborone",2.6,"English,Setswana","BWP","M",["South Africa","Namibia","Zimbabwe","Zambia"],["Namibia","Zimbabwe"]),
("Brazil","BR","S","","south-america","south-america","Brasilia",216.0,"Portuguese","BRL","L",["Argentina","Bolivia","Colombia","French Guiana","Guyana","Paraguay","Peru","Suriname","Uruguay","Venezuela"],["Argentina","Mexico"]),
("Brunei","BN","S","","asia","south-eastern-asia","Bandar Seri Begawan",0.45,"Malay","BND","S",["Malaysia"],["Singapore","Qatar"]),
("Bulgaria","BG","S","","europe","eastern-europe","Sofia",6.5,"Bulgarian","BGN","M",["Romania","Serbia","North Macedonia","Greece","Turkey"],["Romania","Serbia"]),
("Burkina Faso","BF","S","","africa","western-africa","Ouagadougou",22.7,"French","XOF","L",["Mali","Niger","Benin","Togo","Ghana","Ivory Coast"],["Mali","Niger"]),
("Burundi","BI","S","","africa","eastern-africa","Gitega",13.2,"Kirundi,French","BIF","M",["DR Congo","Rwanda","Tanzania"],["Rwanda","DR Congo"]),
("Cabo Verde","CV","S","","africa","western-africa","Praia",0.6,"Portuguese","CVE","S",[],["Sao Tome and Principe","Mauritius"]),
("Cambodia","KH","S","","asia","south-eastern-asia","Phnom Penh",17.0,"Khmer","KHR","M",["Thailand","Laos","Vietnam"],["Vietnam","Laos"]),
("Cameroon","CM","S","","africa","middle-africa","Yaounde",28.6,"French,English","XAF","L",["Nigeria","Chad","Central African Republic","Republic of Congo","Gabon","Equatorial Guinea"],["Nigeria","Gabon"]),
("Canada","CA","S","","north-america","northern-america","Ottawa",39.0,"English,French","CAD","L",["United States"],["United States","Australia"]),
("Central African Republic","CF","S","","africa","middle-africa","Bangui",5.5,"French,Sango","XAF","M",["Cameroon","Chad","Sudan","South Sudan","DR Congo","Republic of Congo"],["Chad","DR Congo"]),
("Chad","TD","S","","africa","middle-africa","N'Djamena",17.7,"French,Arabic","XAF","M",["Libya","Sudan","Central African Republic","Cameroon","Nigeria","Niger"],["Niger","Central African Republic"]),
("Chile","CL","S","","south-america","south-america","Santiago",19.5,"Spanish","CLP","M",["Argentina","Bolivia","Peru"],["Argentina","Peru"]),
("China","CN","S","","asia","eastern-asia","Beijing",1412.0,"Mandarin","CNY","L",["Russia","Mongolia","North Korea","Vietnam","Laos","Myanmar","India","Bhutan","Nepal","Pakistan","Afghanistan","Tajikistan","Kyrgyzstan","Kazakhstan"],["Japan","India"]),
("Colombia","CO","S","","south-america","south-america","Bogota",52.0,"Spanish","COP","L",["Venezuela","Brazil","Peru","Ecuador","Panama"],["Venezuela","Mexico"]),
("Comoros","KM","S","","africa","eastern-africa","Moroni",0.91,"Comorian,Arabic,French","KMF","S",["Madagascar","Mozambique"],["Madagascar","Mauritius"]),
("Republic of Congo","CG","S","","africa","middle-africa","Brazzaville",6.1,"French","XAF","M",["Cameroon","Central African Republic","DR Congo","Angola","Gabon"],["DR Congo","Gabon"]),
("DR Congo","CD","S","","africa","middle-africa","Kinshasa",102.0,"French","CDF","L",["Republic of Congo","Central African Republic","South Sudan","Uganda","Rwanda","Burundi","Tanzania","Zambia","Angola"],["Republic of Congo","Nigeria"]),
("Costa Rica","CR","S","","north-america","central-america","San Jose",5.2,"Spanish","CRC","M",["Nicaragua","Panama"],["Panama","Nicaragua"]),
("Ivory Coast","CI","S","","africa","western-africa","Yamoussoukro",28.9,"French","XOF","L",["Liberia","Guinea","Mali","Burkina Faso","Ghana"],["Ghana","Senegal"]),
("Croatia","HR","S","","europe","southern-europe","Zagreb",3.9,"Croatian","EUR","M",["Slovenia","Hungary","Serbia","Bosnia and Herzegovina","Montenegro"],["Slovenia","Serbia"]),
("Cuba","CU","S","","north-america","caribbean","Havana",11.1,"Spanish","CUP","M",["United States","Jamaica","Haiti","Mexico"],["Puerto Rico","Jamaica"]),
("Cyprus","CY","S","","europe","southern-europe","Nicosia",1.25,"Greek,Turkish","EUR","M",["Turkey","Greece","Syria","Lebanon"],["Greece","Malta"]),
("Czech Republic","CZ","S","","europe","eastern-europe","Prague",10.8,"Czech","CZK","M",["Germany","Poland","Slovakia","Austria"],["Slovakia","Poland"]),
("Denmark","DK","S","","europe","northern-europe","Copenhagen",5.9,"Danish","DKK","M",["Germany","Sweden","Norway"],["Sweden","Norway"]),
("Djibouti","DJ","S","","africa","eastern-africa","Djibouti",1.0,"French,Arabic","DJF","M",["Eritrea","Ethiopia","Somalia"],["Eritrea","Somalia"]),
("Dominica","DM","S","","north-america","caribbean","Roseau",0.07,"English","XCD","S",["Martinique","Guadeloupe"],["Dominican Republic","Grenada"]),
("Dominican Republic","DO","S","","north-america","caribbean","Santo Domingo",11.3,"Spanish","DOP","M",["Haiti"],["Haiti","Puerto Rico"]),
("Ecuador","EC","S","","south-america","south-america","Quito",18.0,"Spanish","USD","M",["Colombia","Peru"],["Peru","Colombia"]),
("Egypt","EG","S","","africa","northern-africa","Cairo",110.0,"Arabic","EGP","L",["Libya","Sudan","Israel","Palestine"],["Morocco","Turkey"]),
("El Salvador","SV","S","","north-america","central-america","San Salvador",6.3,"Spanish","USD","M",["Guatemala","Honduras"],["Honduras","Guatemala"]),
("Equatorial Guinea","GQ","S","","africa","middle-africa","Malabo",1.7,"Spanish,French,Portuguese","XAF","M",["Cameroon","Gabon"],["Gabon","Cameroon"]),
("Eritrea","ER","S","","africa","eastern-africa","Asmara",3.7,"Tigrinya,Arabic","ERN","M",["Sudan","Ethiopia","Djibouti"],["Ethiopia","Djibouti"]),
("Estonia","EE","S","","europe","northern-europe","Tallinn",1.36,"Estonian","EUR","M",["Latvia","Russia","Finland"],["Latvia","Lithuania"]),
("Eswatini","SZ","S","","africa","southern-africa","Mbabane",1.2,"Swazi,English","SZL","M",["South Africa","Mozambique"],["Lesotho","South Africa"]),
("Ethiopia","ET","S","","africa","eastern-africa","Addis Ababa",126.0,"Amharic","ETB","L",["Eritrea","Djibouti","Somalia","Kenya","South Sudan","Sudan"],["Kenya","Nigeria"]),
("Fiji","FJ","S","","oceania","melanesia","Suva",0.93,"English,Fijian,Hindi","FJD","S",["Tonga","Vanuatu","New Zealand"],["Tonga","Samoa"]),
("Finland","FI","S","","europe","northern-europe","Helsinki",5.6,"Finnish,Swedish","EUR","M",["Sweden","Norway","Russia"],["Sweden","Estonia"]),
("France","FR","S","","europe","western-europe","Paris",68.0,"French","EUR","L",["Belgium","Luxembourg","Germany","Switzerland","Italy","Monaco","Spain","Andorra"],["United Kingdom","Germany"]),
("Gabon","GA","S","","africa","middle-africa","Libreville",2.4,"French","XAF","M",["Cameroon","Equatorial Guinea","Republic of Congo"],["Republic of Congo","Equatorial Guinea"]),
("Gambia","GM","S","","africa","western-africa","Banjul",2.7,"English","GMD","M",["Senegal"],["Senegal","Guinea-Bissau"]),
("Georgia","GE","S","","asia","western-asia","Tbilisi",3.7,"Georgian","GEL","M",["Russia","Azerbaijan","Armenia","Turkey"],["Armenia","Azerbaijan"]),
("Germany","DE","S","","europe","western-europe","Berlin",84.5,"German","EUR","L",["Denmark","Poland","Czech Republic","Austria","Switzerland","France","Luxembourg","Belgium","Netherlands"],["France","United Kingdom"]),
("Ghana","GH","S","","africa","western-africa","Accra",33.5,"English","GHS","L",["Ivory Coast","Burkina Faso","Togo"],["Nigeria","Ivory Coast"]),
("Greece","GR","S","","europe","southern-europe","Athens",10.4,"Greek","EUR","M",["Albania","North Macedonia","Bulgaria","Turkey"],["Turkey","Italy"]),
("Grenada","GD","S","","north-america","caribbean","St. George's",0.12,"English","XCD","S",["Trinidad and Tobago","Saint Vincent and the Grenadines"],["Saint Vincent and the Grenadines","Barbados"]),
("Guatemala","GT","S","","north-america","central-america","Guatemala City",17.6,"Spanish","GTQ","M",["Mexico","Belize","Honduras","El Salvador"],["Honduras","El Salvador"]),
("Guinea","GN","S","","africa","western-africa","Conakry",14.0,"French","GNF","M",["Guinea-Bissau","Senegal","Mali","Ivory Coast","Liberia","Sierra Leone"],["Guinea-Bissau","Sierra Leone"]),
("Guinea-Bissau","GW","S","","africa","western-africa","Bissau",2.1,"Portuguese","XOF","M",["Senegal","Guinea"],["Guinea","Senegal"]),
("Guyana","GY","S","","south-america","south-america","Georgetown",0.81,"English","GYD","S",["Venezuela","Brazil","Suriname"],["Suriname","Trinidad and Tobago"]),
("Haiti","HT","S","","north-america","caribbean","Port-au-Prince",11.7,"French,Haitian Creole","HTG","M",["Dominican Republic"],["Dominican Republic","Jamaica"]),
("Honduras","HN","S","","north-america","central-america","Tegucigalpa",10.4,"Spanish","HNL","M",["Guatemala","El Salvador","Nicaragua"],["El Salvador","Guatemala"]),
("Hungary","HU","S","","europe","eastern-europe","Budapest",9.6,"Hungarian","HUF","M",["Austria","Slovakia","Ukraine","Romania","Serbia","Croatia","Slovenia"],["Romania","Czech Republic"]),
("Iceland","IS","S","","europe","northern-europe","Reykjavik",0.38,"Icelandic","ISK","S",["Greenland","United Kingdom","Norway"],["Greenland","Norway"]),
("India","IN","S","","asia","southern-asia","New Delhi",1428.0,"Hindi,English","INR","L",["Pakistan","China","Nepal","Bhutan","Bangladesh","Myanmar","Sri Lanka"],["China","Pakistan"]),
("Indonesia","ID","S","","asia","south-eastern-asia","Jakarta",277.0,"Indonesian","IDR","L",["Malaysia","Papua New Guinea","East Timor","Australia"],["Malaysia","Philippines"]),
("Iran","IR","S","","asia","western-asia","Tehran",88.6,"Persian","IRR","L",["Iraq","Turkey","Armenia","Azerbaijan","Turkmenistan","Afghanistan","Pakistan"],["Iraq","Turkey"]),
("Iraq","IQ","S","","asia","western-asia","Baghdad",44.5,"Arabic,Kurdish","IQD","L",["Turkey","Iran","Kuwait","Saudi Arabia","Jordan","Syria"],["Iran","Syria"]),
("Ireland","IE","S","","europe","northern-europe","Dublin",5.1,"English,Irish","EUR","M",["United Kingdom"],["United Kingdom","Scotland"]),
("Israel","IL","S","","asia","western-asia","Jerusalem",9.8,"Hebrew,Arabic","ILS","M",["Lebanon","Syria","Jordan","Egypt","Palestine"],["Palestine","Lebanon"]),
("Italy","IT","S","","europe","southern-europe","Rome",59.0,"Italian","EUR","L",["France","Switzerland","Austria","Slovenia","San Marino","Vatican City"],["Spain","France"]),
("Jamaica","JM","S","","north-america","caribbean","Kingston",3.0,"English","JMD","M",["Cuba","Haiti"],["Trinidad and Tobago","Barbados"]),
("Japan","JP","S","","asia","eastern-asia","Tokyo",124.0,"Japanese","JPY","L",["South Korea","China","Russia"],["South Korea","China"]),
("Jordan","JO","S","","asia","western-asia","Amman",11.4,"Arabic","JOD","M",["Syria","Iraq","Saudi Arabia","Israel","Palestine"],["Israel","Lebanon"]),
("Kazakhstan","KZ","S","","asia","central-asia","Astana",19.8,"Kazakh,Russian","KZT","M",["Russia","China","Kyrgyzstan","Uzbekistan","Turkmenistan"],["Uzbekistan","Mongolia"]),
("Kenya","KE","S","","africa","eastern-africa","Nairobi",55.0,"Swahili,English","KES","L",["Ethiopia","Somalia","Tanzania","Uganda","South Sudan"],["Tanzania","Ethiopia"]),
("Kiribati","KI","S","","oceania","micronesia","Tarawa",0.13,"English,Gilbertese","AUD","S",["Marshall Islands","Nauru"],["Tuvalu","Marshall Islands"]),
("North Korea","KP","S","","asia","eastern-asia","Pyongyang",26.1,"Korean","KPW","L",["South Korea","China","Russia"],["South Korea","China"]),
("South Korea","KR","S","","asia","eastern-asia","Seoul",51.7,"Korean","KRW","L",["North Korea","Japan","China"],["North Korea","Japan"]),
("Kuwait","KW","S","","asia","western-asia","Kuwait City",4.3,"Arabic","KWD","M",["Iraq","Saudi Arabia"],["Qatar","Bahrain"]),
("Kyrgyzstan","KG","S","","asia","central-asia","Bishkek",7.0,"Kyrgyz,Russian","KGS","M",["Kazakhstan","China","Tajikistan","Uzbekistan"],["Tajikistan","Kazakhstan"]),
("Laos","LA","S","","asia","south-eastern-asia","Vientiane",7.5,"Lao","LAK","M",["Myanmar","China","Vietnam","Cambodia","Thailand"],["Cambodia","Vietnam"]),
("Latvia","LV","S","","europe","northern-europe","Riga",1.8,"Latvian","EUR","M",["Estonia","Lithuania","Russia","Belarus"],["Lithuania","Estonia"]),
("Lebanon","LB","S","","asia","western-asia","Beirut",5.5,"Arabic","LBP","M",["Syria","Israel"],["Israel","Jordan"]),
("Lesotho","LS","S","","africa","southern-africa","Maseru",2.3,"Sesotho,English","LSL","M",["South Africa"],["Eswatini","South Africa"]),
("Liberia","LR","S","","africa","western-africa","Monrovia",5.4,"English","LRD","M",["Guinea","Ivory Coast","Sierra Leone"],["Sierra Leone","Guinea"]),
("Libya","LY","S","","africa","northern-africa","Tripoli",7.0,"Arabic","LYD","M",["Tunisia","Algeria","Niger","Chad","Sudan","Egypt"],["Tunisia","Algeria"]),
("Liechtenstein","LI","S","","europe","western-europe","Vaduz",0.04,"German","CHF","S",["Austria","Switzerland"],["Monaco","Andorra"]),
("Lithuania","LT","S","","europe","northern-europe","Vilnius",2.8,"Lithuanian","EUR","M",["Latvia","Belarus","Poland","Russia"],["Latvia","Poland"]),
("Luxembourg","LU","S","","europe","western-europe","Luxembourg City",0.66,"Luxembourgish,French,German","EUR","S",["Belgium","France","Germany"],["Belgium","Liechtenstein"]),
("Madagascar","MG","S","","africa","eastern-africa","Antananarivo",30.3,"Malagasy,French","MGA","L",["Mozambique","Comoros"],["Mozambique","Mauritius"]),
("Malawi","MW","S","","africa","eastern-africa","Lilongwe",20.4,"English,Chichewa","MWK","L",["Mozambique","Tanzania","Zambia"],["Zambia","Mozambique"]),
("Malaysia","MY","S","","asia","south-eastern-asia","Kuala Lumpur",33.9,"Malay","MYR","L",["Thailand","Indonesia","Brunei","Singapore","Philippines"],["Singapore","Thailand"]),
("Maldives","MV","S","","asia","southern-asia","Male",0.52,"Dhivehi","MVR","S",["Sri Lanka","India"],["Sri Lanka","Seychelles"]),
("Mali","ML","S","","africa","western-africa","Bamako",22.4,"French","XOF","L",["Algeria","Niger","Burkina Faso","Ivory Coast","Guinea","Senegal","Mauritania"],["Niger","Burkina Faso"]),
("Malta","MT","S","","europe","southern-europe","Valletta",0.54,"Maltese,English","EUR","S",["Italy","Tunisia"],["Cyprus","Sicily"]),
("Marshall Islands","MH","S","","oceania","micronesia","Majuro",0.04,"Marshallese,English","USD","S",["Kiribati","Micronesia"],["Micronesia","Palau"]),
("Mauritania","MR","S","","africa","western-africa","Nouakchott",4.9,"Arabic","MRU","M",["Western Sahara","Algeria","Mali","Senegal"],["Mali","Western Sahara"]),
("Mauritius","MU","S","","africa","eastern-africa","Port Louis",1.3,"English,French,Creole","MUR","M",["Madagascar","Reunion"],["Seychelles","Maldives"]),
("Mexico","MX","S","","north-america","central-america","Mexico City",129.0,"Spanish","MXN","L",["United States","Guatemala","Belize"],["United States","Colombia"]),
("Micronesia","FM","S","","oceania","micronesia","Palikir",0.11,"English","USD","S",["Palau","Marshall Islands","Papua New Guinea"],["Marshall Islands","Palau"]),
("Moldova","MD","S","","europe","eastern-europe","Chisinau",2.6,"Romanian","MDL","M",["Romania","Ukraine"],["Romania","Ukraine"]),
("Monaco","MC","S","","europe","western-europe","Monaco",0.04,"French","EUR","S",["France"],["Liechtenstein","Andorra"]),
("Mongolia","MN","S","","asia","eastern-asia","Ulaanbaatar",3.4,"Mongolian","MNT","M",["Russia","China"],["Kazakhstan","China"]),
("Montenegro","ME","S","","europe","southern-europe","Podgorica",0.62,"Montenegrin","EUR","S",["Croatia","Bosnia and Herzegovina","Serbia","Kosovo","Albania"],["Serbia","Croatia"]),
("Morocco","MA","S","","africa","northern-africa","Rabat",37.5,"Arabic,Berber","MAD","L",["Algeria","Western Sahara","Spain"],["Algeria","Tunisia"]),
("Mozambique","MZ","S","","africa","eastern-africa","Maputo",33.9,"Portuguese","MZN","L",["Tanzania","Malawi","Zambia","Zimbabwe","South Africa","Eswatini","Madagascar"],["Tanzania","Angola"]),
("Myanmar","MM","S","","asia","south-eastern-asia","Naypyidaw",54.4,"Burmese","MMK","L",["Bangladesh","India","China","Laos","Thailand"],["Thailand","Laos"]),
("Namibia","NA","S","","africa","southern-africa","Windhoek",2.6,"English","NAD","M",["Angola","Zambia","Botswana","South Africa"],["Botswana","South Africa"]),
("Nauru","NR","S","","oceania","micronesia","Yaren",0.01,"Nauruan,English","AUD","S",["Kiribati"],["Tuvalu","Kiribati"]),
("Nepal","NP","S","","asia","southern-asia","Kathmandu",30.9,"Nepali","NPR","L",["China","India"],["Bhutan","Tibet"]),
("Netherlands","NL","S","","europe","western-europe","Amsterdam",17.7,"Dutch","EUR","M",["Belgium","Germany"],["Belgium","Denmark"]),
("New Zealand","NZ","S","","oceania","australia-new-zealand","Wellington",5.2,"English,Maori","NZD","M",["Australia"],["Australia","Fiji"]),
("Nicaragua","NI","S","","north-america","central-america","Managua",7.0,"Spanish","NIO","M",["Honduras","Costa Rica"],["Honduras","Costa Rica"]),
("Niger","NE","S","","africa","western-africa","Niamey",27.2,"French","XOF","L",["Algeria","Libya","Chad","Nigeria","Benin","Burkina Faso","Mali"],["Chad","Mali"]),
("Nigeria","NG","S","","africa","western-africa","Abuja",224.0,"English","NGN","L",["Benin","Niger","Chad","Cameroon"],["Ghana","South Africa"]),
("North Macedonia","MK","S","","europe","southern-europe","Skopje",1.8,"Macedonian,Albanian","MKD","M",["Kosovo","Serbia","Bulgaria","Greece","Albania"],["Greece","Bulgaria"]),
("Norway","NO","S","","europe","northern-europe","Oslo",5.5,"Norwegian","NOK","M",["Sweden","Finland","Russia"],["Sweden","Denmark"]),
("Oman","OM","S","","asia","western-asia","Muscat",4.6,"Arabic","OMR","M",["UAE","Saudi Arabia","Yemen"],["UAE","Yemen"]),
("Pakistan","PK","S","","asia","southern-asia","Islamabad",231.0,"Urdu,English","PKR","L",["India","China","Afghanistan","Iran"],["India","Bangladesh"]),
("Palau","PW","S","","oceania","micronesia","Ngerulmud",0.02,"Palauan,English","USD","S",["Micronesia","Philippines"],["Micronesia","Marshall Islands"]),
("Palestine","PS","DI","","asia","western-asia","Ramallah",5.4,"Arabic","ILS","M",["Israel","Egypt","Jordan"],["Israel","Jordan"]),
("Panama","PA","S","","north-america","central-america","Panama City",4.4,"Spanish","PAB","M",["Costa Rica","Colombia"],["Costa Rica","Colombia"]),
("Papua New Guinea","PG","S","","oceania","melanesia","Port Moresby",10.1,"English,Tok Pisin,Hiri Motu","PGK","M",["Indonesia","Australia"],["Indonesia","Solomon Islands"]),
("Paraguay","PY","S","","south-america","south-america","Asuncion",7.4,"Spanish,Guarani","PYG","M",["Argentina","Bolivia","Brazil"],["Uruguay","Bolivia"]),
("Peru","PE","S","","south-america","south-america","Lima",34.0,"Spanish","PEN","L",["Ecuador","Colombia","Brazil","Bolivia","Chile"],["Bolivia","Ecuador"]),
("Philippines","PH","S","","asia","south-eastern-asia","Manila",117.0,"Filipino,English","PHP","L",["Taiwan","Malaysia","Indonesia","Vietnam"],["Indonesia","Malaysia"]),
("Poland","PL","S","","europe","eastern-europe","Warsaw",37.7,"Polish","PLN","L",["Germany","Czech Republic","Slovakia","Ukraine","Belarus","Lithuania","Russia"],["Czech Republic","Germany"]),
("Portugal","PT","S","","europe","southern-europe","Lisbon",10.3,"Portuguese","EUR","M",["Spain"],["Spain","Brazil"]),
("Qatar","QA","S","","asia","western-asia","Doha",2.9,"Arabic","QAR","M",["Saudi Arabia","Bahrain","UAE"],["UAE","Bahrain"]),
("Romania","RO","S","","europe","eastern-europe","Bucharest",19.0,"Romanian","RON","M",["Ukraine","Moldova","Hungary","Serbia","Bulgaria"],["Bulgaria","Moldova"]),
("Russia","RU","S","","europe","eastern-europe","Moscow",144.0,"Russian","RUB","L",["Norway","Finland","Estonia","Latvia","Lithuania","Poland","Belarus","Ukraine","Georgia","Azerbaijan","Kazakhstan","China","Mongolia","North Korea"],["China","United States"]),
("Rwanda","RW","S","","africa","eastern-africa","Kigali",14.1,"Kinyarwanda,English,French","RWF","M",["Uganda","Tanzania","Burundi","DR Congo"],["Burundi","Uganda"]),
("Saint Kitts and Nevis","KN","S","","north-america","caribbean","Basseterre",0.05,"English","XCD","S",["Antigua and Barbuda"],["Antigua and Barbuda","Saint Lucia"]),
("Saint Lucia","LC","S","","north-america","caribbean","Castries",0.18,"English","XCD","S",["Martinique","Saint Vincent and the Grenadines"],["Saint Vincent and the Grenadines","Barbados"]),
("Saint Vincent and the Grenadines","VC","S","","north-america","caribbean","Kingstown",0.11,"English","XCD","S",["Saint Lucia","Grenada","Barbados"],["Grenada","Saint Lucia"]),
("Samoa","WS","S","","oceania","polynesia","Apia",0.22,"Samoan,English","WST","S",["American Samoa","Tonga"],["American Samoa","Tonga"]),
("San Marino","SM","S","","europe","southern-europe","San Marino",0.03,"Italian","EUR","S",["Italy"],["Vatican City","Liechtenstein"]),
("Sao Tome and Principe","ST","S","","africa","middle-africa","Sao Tome",0.23,"Portuguese","STN","S",["Gabon","Equatorial Guinea"],["Cabo Verde","Comoros"]),
("Saudi Arabia","SA","S","","asia","western-asia","Riyadh",36.9,"Arabic","SAR","L",["Jordan","Iraq","Kuwait","Bahrain","Qatar","UAE","Oman","Yemen"],["UAE","Iran"]),
("Senegal","SN","S","","africa","western-africa","Dakar",17.7,"French","XOF","M",["Mauritania","Mali","Guinea","Guinea-Bissau","Gambia"],["Gambia","Mali"]),
("Serbia","RS","S","","europe","southern-europe","Belgrade",6.6,"Serbian","RSD","M",["Hungary","Romania","Bulgaria","North Macedonia","Kosovo","Montenegro","Bosnia and Herzegovina","Croatia"],["Croatia","Bosnia and Herzegovina"]),
("Seychelles","SC","S","","africa","eastern-africa","Victoria",0.1,"Seychellois Creole,English,French","SCR","S",["Madagascar","Mauritius"],["Maldives","Mauritius"]),
("Sierra Leone","SL","S","","africa","western-africa","Freetown",8.6,"English","SLE","M",["Guinea","Liberia"],["Liberia","Guinea"]),
("Singapore","SG","S","","asia","south-eastern-asia","Singapore",6.0,"English,Malay,Mandarin,Tamil","SGD","M",["Malaysia","Indonesia"],["Hong Kong","Malaysia"]),
("Slovakia","SK","S","","europe","eastern-europe","Bratislava",5.4,"Slovak","EUR","M",["Czech Republic","Poland","Ukraine","Hungary","Austria"],["Czech Republic","Slovenia"]),
("Slovenia","SI","S","","europe","southern-europe","Ljubljana",2.1,"Slovenian","EUR","M",["Italy","Austria","Hungary","Croatia"],["Slovakia","Croatia"]),
("Solomon Islands","SB","S","","oceania","melanesia","Honiara",0.72,"English","SBD","S",["Papua New Guinea","Vanuatu"],["Papua New Guinea","Vanuatu"]),
("Somalia","SO","S","","africa","eastern-africa","Mogadishu",18.1,"Somali,Arabic","SOS","M",["Djibouti","Ethiopia","Kenya"],["Ethiopia","Djibouti"]),
("South Africa","ZA","S","","africa","southern-africa","Pretoria",60.4,"Zulu,Xhosa,Afrikaans,English","ZAR","L",["Namibia","Botswana","Zimbabwe","Mozambique","Eswatini","Lesotho"],["Nigeria","Kenya"]),
("South Sudan","SS","S","","africa","eastern-africa","Juba",11.1,"English","SSP","M",["Sudan","Ethiopia","Kenya","Uganda","DR Congo","Central African Republic"],["Sudan","Uganda"]),
("Spain","ES","S","","europe","southern-europe","Madrid",47.8,"Spanish","EUR","L",["France","Portugal","Andorra","Morocco","Gibraltar"],["Portugal","Italy"]),
("Sri Lanka","LK","S","","asia","southern-asia","Colombo",22.2,"Sinhala,Tamil","LKR","L",["India","Maldives"],["Maldives","India"]),
("Sudan","SD","S","","africa","northern-africa","Khartoum",47.9,"Arabic,English","SDG","L",["Egypt","Libya","Chad","Central African Republic","South Sudan","Ethiopia","Eritrea"],["South Sudan","Egypt"]),
("Suriname","SR","S","","south-america","south-america","Paramaribo",0.62,"Dutch","SRD","S",["Guyana","Brazil","French Guiana"],["Guyana","French Guiana"]),
("Sweden","SE","S","","europe","northern-europe","Stockholm",10.5,"Swedish","SEK","M",["Norway","Finland","Denmark"],["Norway","Finland"]),
("Switzerland","CH","S","","europe","western-europe","Bern",8.8,"German,French,Italian,Romansh","CHF","M",["Germany","France","Italy","Austria","Liechtenstein"],["Austria","Sweden"]),
("Syria","SY","S","","asia","western-asia","Damascus",22.1,"Arabic","SYP","L",["Turkey","Iraq","Jordan","Israel","Lebanon"],["Iraq","Lebanon"]),
("Taiwan","TW","DI","","asia","eastern-asia","Taipei",23.9,"Mandarin","TWD","L",["China","Japan","Philippines"],["China","Hong Kong"]),
("Tajikistan","TJ","S","","asia","central-asia","Dushanbe",10.1,"Tajik","TJS","M",["China","Kyrgyzstan","Uzbekistan","Afghanistan"],["Kyrgyzstan","Afghanistan"]),
("Tanzania","TZ","S","","africa","eastern-africa","Dodoma",65.5,"Swahili,English","TZS","L",["Kenya","Uganda","Rwanda","Burundi","DR Congo","Zambia","Malawi","Mozambique"],["Kenya","Uganda"]),
("Thailand","TH","S","","asia","south-eastern-asia","Bangkok",71.8,"Thai","THB","L",["Myanmar","Laos","Cambodia","Malaysia"],["Vietnam","Indonesia"]),
("East Timor","TL","S","","asia","south-eastern-asia","Dili",1.3,"Portuguese,Tetum","USD","M",["Indonesia"],["Indonesia","Papua New Guinea"]),
("Togo","TG","S","","africa","western-africa","Lome",8.8,"French","XOF","M",["Ghana","Burkina Faso","Benin"],["Benin","Ghana"]),
("Tonga","TO","S","","oceania","polynesia","Nukualofa",0.11,"Tongan,English","TOP","S",["Fiji","Samoa"],["Samoa","Fiji"]),
("Trinidad and Tobago","TT","S","","north-america","caribbean","Port of Spain",1.5,"English","TTD","M",["Venezuela","Grenada","Barbados"],["Jamaica","Barbados"]),
("Tunisia","TN","S","","africa","northern-africa","Tunis",12.5,"Arabic","TND","M",["Algeria","Libya"],["Morocco","Algeria"]),
("Turkey","TR","S","","asia","western-asia","Ankara",85.8,"Turkish","TRY","L",["Greece","Bulgaria","Georgia","Armenia","Azerbaijan","Iran","Iraq","Syria"],["Greece","Iran"]),
("Turkmenistan","TM","S","","asia","central-asia","Ashgabat",6.5,"Turkmen","TMT","M",["Kazakhstan","Uzbekistan","Afghanistan","Iran"],["Uzbekistan","Kazakhstan"]),
("Tuvalu","TV","S","","oceania","polynesia","Funafuti",0.01,"Tuvaluan,English","AUD","S",["Fiji","Kiribati"],["Nauru","Kiribati"]),
("Uganda","UG","S","","africa","eastern-africa","Kampala",48.6,"English,Swahili","UGX","L",["South Sudan","Kenya","Tanzania","Rwanda","DR Congo"],["Kenya","Rwanda"]),
("Ukraine","UA","S","","europe","eastern-europe","Kyiv",37.0,"Ukrainian","UAH","L",["Russia","Belarus","Poland","Slovakia","Hungary","Romania","Moldova"],["Russia","Poland"]),
("UAE","AE","S","","asia","western-asia","Abu Dhabi",10.0,"Arabic","AED","M",["Saudi Arabia","Oman"],["Qatar","Saudi Arabia"]),
("United Kingdom","GB","S","","europe","northern-europe","London",67.7,"English","GBP","L",["Ireland","France"],["France","United States"]),
("United States","US","S","","north-america","northern-america","Washington D.C.",335.0,"English","USD","L",["Canada","Mexico"],["Canada","United Kingdom"]),
("Uruguay","UY","S","","south-america","south-america","Montevideo",3.4,"Spanish","UYU","M",["Argentina","Brazil"],["Argentina","Paraguay"]),
("Uzbekistan","UZ","S","","asia","central-asia","Tashkent",35.6,"Uzbek","UZS","L",["Kazakhstan","Kyrgyzstan","Tajikistan","Afghanistan","Turkmenistan"],["Kazakhstan","Tajikistan"]),
("Vanuatu","VU","S","","oceania","melanesia","Port Vila",0.33,"Bislama,English,French","VUV","S",["Fiji","New Caledonia","Solomon Islands"],["Fiji","New Caledonia"]),
("Vatican City","VA","S","","europe","southern-europe","Vatican City",0.0008,"Italian,Latin","EUR","S",["Italy"],["San Marino","Monaco"]),
("Venezuela","VE","S","","south-america","south-america","Caracas",28.4,"Spanish","VES","L",["Colombia","Brazil","Guyana","Trinidad and Tobago"],["Colombia","Cuba"]),
("Vietnam","VN","S","","asia","south-eastern-asia","Hanoi",99.5,"Vietnamese","VND","L",["China","Laos","Cambodia"],["Thailand","Cambodia"]),
("Yemen","YE","S","","asia","western-asia","Sanaa",34.4,"Arabic","YER","L",["Saudi Arabia","Oman"],["Oman","Somalia"]),
("Zambia","ZM","S","","africa","eastern-africa","Lusaka",20.6,"English","ZMW","L",["DR Congo","Tanzania","Malawi","Mozambique","Zimbabwe","Botswana","Namibia","Angola"],["Zimbabwe","Malawi"]),
("Zimbabwe","ZW","S","","africa","eastern-africa","Harare",16.7,"English,Shona,Ndebele","ZWL","M",["Zambia","Mozambique","South Africa","Botswana"],["Zambia","South Africa"]),
# ============ TERRITORIES & DEPENDENCIES ============
("Puerto Rico","PR","T","United States","north-america","caribbean","San Juan",3.2,"Spanish,English","USD","M",["Dominican Republic","US Virgin Islands"],["Dominican Republic","Cuba"]),
("Hong Kong","HK","SAR","China","asia","eastern-asia","Hong Kong",7.5,"Cantonese,English","HKD","M",["China","Macau"],["Singapore","Macau"]),
("Macau","MO","SAR","China","asia","eastern-asia","Macau",0.69,"Cantonese,Portuguese","MOP","S",["China","Hong Kong"],["Hong Kong","Las Vegas"]),
("Greenland","GL","T","Denmark","north-america","northern-america","Nuuk",0.06,"Greenlandic,Danish","DKK","S",["Canada","Iceland"],["Iceland","Faroe Islands"]),
("Faroe Islands","FO","T","Denmark","europe","northern-europe","Torshavn",0.05,"Faroese,Danish","DKK","S",["Iceland","Norway"],["Iceland","Greenland"]),
("French Guiana","GF","T","France","south-america","south-america","Cayenne",0.31,"French","EUR","S",["Brazil","Suriname"],["Suriname","Guyana"]),
("Guadeloupe","GP","T","France","north-america","caribbean","Basse-Terre",0.4,"French","EUR","S",["Dominica","Antigua and Barbuda","Montserrat"],["Martinique","Reunion"]),
("Martinique","MQ","T","France","north-america","caribbean","Fort-de-France",0.37,"French","EUR","S",["Dominica","Saint Lucia"],["Guadeloupe","Reunion"]),
("Reunion","RE","T","France","africa","eastern-africa","Saint-Denis",0.9,"French","EUR","S",["Madagascar","Mauritius"],["Mauritius","Martinique"]),
("Mayotte","YT","T","France","africa","eastern-africa","Mamoudzou",0.33,"French","EUR","S",["Comoros","Madagascar"],["Comoros","Reunion"]),
("French Polynesia","PF","T","France","oceania","polynesia","Papeete",0.28,"French,Tahitian","XPF","S",["Cook Islands"],["Hawaii","New Caledonia"]),
("New Caledonia","NC","T","France","oceania","melanesia","Noumea",0.27,"French","XPF","S",["Vanuatu","Fiji"],["Vanuatu","French Polynesia"]),
("Saint Martin","MF","T","France","north-america","caribbean","Marigot",0.04,"French","EUR","S",["Sint Maarten","Anguilla"],["Sint Maarten","Saint Barthelemy"]),
("Saint Barthelemy","BL","T","France","north-america","caribbean","Gustavia",0.01,"French","EUR","S",["Saint Martin","Anguilla"],["Saint Martin","Guadeloupe"]),
("Wallis and Futuna","WF","T","France","oceania","polynesia","Mata-Utu",0.01,"French,Wallisian","XPF","S",["Samoa","Fiji"],["Samoa","French Polynesia"]),
("Saint Pierre and Miquelon","PM","T","France","north-america","northern-america","Saint-Pierre",0.006,"French","EUR","S",["Canada"],["Greenland","Faroe Islands"]),
("US Virgin Islands","VI","T","United States","north-america","caribbean","Charlotte Amalie",0.1,"English","USD","S",["Puerto Rico","British Virgin Islands"],["British Virgin Islands","Puerto Rico"]),
("Guam","GU","T","United States","oceania","micronesia","Hagatna",0.17,"English,Chamorro","USD","S",["Northern Mariana Islands","Micronesia"],["Northern Mariana Islands","Hawaii"]),
("American Samoa","AS","T","United States","oceania","polynesia","Pago Pago",0.05,"Samoan,English","USD","S",["Samoa","Tonga"],["Samoa","Tonga"]),
("Northern Mariana Islands","MP","T","United States","oceania","micronesia","Saipan",0.05,"English,Chamorro,Carolinian","USD","S",["Guam"],["Guam","Palau"]),
("British Virgin Islands","VG","T","United Kingdom","north-america","caribbean","Road Town",0.03,"English","USD","S",["US Virgin Islands","Anguilla"],["US Virgin Islands","Cayman Islands"]),
("Cayman Islands","KY","T","United Kingdom","north-america","caribbean","George Town",0.07,"English","KYD","S",["Cuba","Jamaica"],["British Virgin Islands","Bermuda"]),
("Bermuda","BM","T","United Kingdom","north-america","northern-america","Hamilton",0.06,"English","BMD","S",["United States"],["Bahamas","Cayman Islands"]),
("Turks and Caicos","TC","T","United Kingdom","north-america","caribbean","Cockburn Town",0.04,"English","USD","S",["Bahamas","Haiti"],["Bahamas","Cayman Islands"]),
("Anguilla","AI","T","United Kingdom","north-america","caribbean","The Valley",0.02,"English","XCD","S",["Saint Martin","British Virgin Islands"],["British Virgin Islands","Sint Maarten"]),
("Montserrat","MS","T","United Kingdom","north-america","caribbean","Plymouth",0.005,"English","XCD","S",["Antigua and Barbuda","Guadeloupe"],["Antigua and Barbuda","Dominica"]),
("Gibraltar","GI","T","United Kingdom","europe","southern-europe","Gibraltar",0.03,"English","GIP","S",["Spain"],["Malta","Ceuta"]),
("Falkland Islands","FK","T","United Kingdom","south-america","south-america","Stanley",0.004,"English","FKP","S",["Argentina"],["South Georgia","Argentina"]),
("Saint Helena","SH","T","United Kingdom","africa","western-africa","Jamestown",0.005,"English","SHP","S",[],["Ascension Island","Tristan da Cunha"]),
("Pitcairn Islands","PN","T","United Kingdom","oceania","polynesia","Adamstown",0.00005,"English","NZD","S",[],["Easter Island","Norfolk Island"]),
("Isle of Man","IM","D","United Kingdom","europe","northern-europe","Douglas",0.08,"English,Manx","GBP","S",["United Kingdom","Ireland"],["Jersey","Guernsey"]),
("Jersey","JE","D","United Kingdom","europe","northern-europe","Saint Helier",0.11,"English,French","GBP","S",["France","Guernsey"],["Guernsey","Isle of Man"]),
("Guernsey","GG","D","United Kingdom","europe","northern-europe","Saint Peter Port",0.06,"English,French","GBP","S",["France","Jersey"],["Jersey","Isle of Man"]),
("Aruba","AW","T","Netherlands","north-america","caribbean","Oranjestad",0.11,"Papiamento,Dutch","AWG","S",["Curacao","Venezuela"],["Curacao","Bonaire"]),
("Curacao","CW","T","Netherlands","north-america","caribbean","Willemstad",0.15,"Papiamento,Dutch","ANG","S",["Aruba","Bonaire","Venezuela"],["Aruba","Bonaire"]),
("Sint Maarten","SX","T","Netherlands","north-america","caribbean","Philipsburg",0.04,"Dutch,English","ANG","S",["Saint Martin","Anguilla"],["Saint Martin","Aruba"]),
("Bonaire","BQ","T","Netherlands","north-america","caribbean","Kralendijk",0.02,"Papiamento,Dutch","USD","S",["Curacao","Venezuela"],["Curacao","Aruba"]),
("Cook Islands","CK","T","New Zealand","oceania","polynesia","Avarua",0.02,"English,Cook Islands Maori","NZD","S",["French Polynesia","Samoa"],["Niue","Samoa"]),
("Niue","NU","T","New Zealand","oceania","polynesia","Alofi",0.002,"Niuean,English","NZD","S",["Tonga","Cook Islands"],["Cook Islands","Tonga"]),
("Tokelau","TK","T","New Zealand","oceania","polynesia","Atafu",0.002,"Tokelauan,English","NZD","S",["Samoa"],["Tuvalu","Wallis and Futuna"]),
("Christmas Island","CX","T","Australia","asia","south-eastern-asia","Flying Fish Cove",0.002,"English","AUD","S",["Indonesia"],["Cocos Islands","Norfolk Island"]),
("Cocos Islands","CC","T","Australia","asia","south-eastern-asia","West Island",0.0006,"English,Malay","AUD","S",["Christmas Island"],["Christmas Island","Maldives"]),
("Norfolk Island","NF","T","Australia","oceania","australia-new-zealand","Kingston",0.002,"English,Norfuk","AUD","S",["New Zealand","New Caledonia"],["Lord Howe Island","Pitcairn Islands"]),
("Western Sahara","EH","DI","","africa","northern-africa","Laayoune",0.6,"Arabic,Berber","MAD","S",["Morocco","Algeria","Mauritania"],["Morocco","Palestine"]),
("Kosovo","XK","DI","","europe","southern-europe","Pristina",1.8,"Albanian,Serbian","EUR","M",["Serbia","North Macedonia","Albania","Montenegro"],["Albania","North Macedonia"]),
("Svalbard","SJ","T","Norway","europe","northern-europe","Longyearbyen",0.003,"Norwegian","NOK","S",["Norway"],["Greenland","Iceland"]),
("Aland Islands","AX","T","Finland","europe","northern-europe","Mariehamn",0.03,"Swedish","EUR","S",["Finland","Sweden"],["Faroe Islands","Gotland"]),
("South Georgia","GS","T","United Kingdom","south-america","south-america","King Edward Point",0.00003,"English","GBP","S",["Falkland Islands"],["Falkland Islands","Antarctica"]),
]

def build_registry():
    type_map = {"S": "sovereign", "T": "territory", "D": "dependency", "SAR": "special-admin-region", "DI": "disputed"}
    entities = []
    for e in ENTITIES:
        name, iso, etype, parent, continent, sub_region, capital, pop, langs, currency, size, neighbors, comparisons = e
        entities.append({
            "name": name,
            "iso_code": iso,
            "type": type_map.get(etype, etype),
            "parent_entity": parent,
            "continent": continent,
            "sub_region": sub_region,
            "capital": capital,
            "population_millions": pop,
            "languages": langs.split(","),
            "currency": currency,
            "size_class": {"L": "large", "M": "medium", "S": "small"}[size],
            "neighbors": neighbors,
            "common_comparisons": comparisons,
        })

    registry = {
        "version": "1.0",
        "generated_date": "2026-02-08",
        "total_entities": len(entities),
        "entities": {slugify(e["name"]): e for e in entities},
    }

    import os
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "entity_registry.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(registry, f, indent=2, ensure_ascii=False)
    print(f"Generated {len(entities)} entities -> {out}")

def slugify(text):
    text = text.lower().strip()
    import re
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[-\s]+', '-', text)
    return text

if __name__ == "__main__":
    build_registry()
